### ISSUE TITLE
SSH Host Key not properly generated

### ISSUE THREAD

**Issue by timkenhan** [usbarmory/usbarmory-debian-base_image#52]
I would like to bring to your attention that the host keys that are supposed to be generated during the sshd setup do not seem to be properly generated.

For now, creating it manually seem to fix the issue.

**Comment by abarisani** [comment]
SSH keys are generated at first boot, we tested that there are no issues with this. It is not clear to me what you mean with "properly generated". Be aware that if you interrupt the first boot at generation (power loss, premature disconnection, etc.) that will leave you with corrupted keys as they won't be correctly re-generated at the following boot, maybe that's what happened in your case.

**Comment by abarisani** [comment]
SSH keys are generated at first boot, we tested that there are no issues with this. It is not clear to me what you mean with "properly generated". Be aware that if you interrupt the first boot at generation (power loss, premature disconnection, etc.) that will leave you with corrupted keys as they won't be correctly re-generated at the following boot, maybe that's what happened in your case.

**Comment by abarisani** [comment]
Please reopen if necessary.
