### ISSUE TITLE
CONFIG_BINFMT_MISC not set for Kernel

### ISSUE THREAD

**Issue by bluecmd** [usbarmory/usbarmory-debian-base_image#54]
Hello,

I would like to be able to use qemu-user to emulate other CPU-architectures on my USB Armory - but for that to be nice and easy to work with binfmt_misc needs to be supported by the host kernel.

See:
```
usbarmory@usbarmory:~$ sudo update-binfmts --enable qemu-x86_64
mount: /proc/sys/fs/binfmt_misc: mount point does not exist.
update-binfmts: warning: Couldn't mount the binfmt_misc filesystem on /proc/sys/fs/binfmt_misc.
usbarmory@usbarmory:~$ grep BINFMT_MISC /boot/config-5.15.78-0-usbarmory 
# CONFIG_BINFMT_MISC is not set
```

Would you consider enabling this as a module?

**Comment by andrejro** [comment]
Done: https://github.com/usbarmory/usbarmory/commit/a60d0d326ca4450e8c19bc291f8ae129026c499a
The next release will have the binfmt_misc support enabled.
