### ISSUE TITLE
Flashing eMMC Assistance

### ISSUE THREAD

**Issue by tweathers-sec** [usbarmory/usbarmory-debian-base_image#56]
I recently purchased several MkII's but cannot see any of the devices when attaching them to my computer (M1 MacBook Ventura). I've read through all the documentation, but I must be missing something. Can you point me in the right direction for installing the official debain directly on the eMMC. Thanks in advance. 

Running `diskutil  list` only returns my main disk.

**Comment by andrejro** [comment]
Install first the Debian image directly on a microSD card as explained at
https://github.com/usbarmory/usbarmory-debian-base_image/releases/tag/20230315

Once the system is up and running you can flash the eMMC image on the internal /dev/mmcblk1 device as done for the microSD one.
